### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by andreistepanyuk**

### CODE REVIEW

**Comment by jpgsantos** [comment]
What is the difference between:
Viswan_2018_for_STEPS_optimised.xlsx and Viswan_2018_optimized.xlsx
Viswan_2018_for_STEPS.xlsx and Viswan_2018.xlsx
Or other seemingly repeated files?

Aren't the files inside the "SBtabVFGEN-master" folder basically a copy from the "https://github.com/a-kramer/SBtabVFGEN" repository? This is already linked in the main "github.com/jpgsantos/Subcellular_workflow" repository and as susch shouldn't be repeated here.

Appart from this apparent repetitions this seems to be ok although I don't have the ability to run the code on my machine

**Comment by andreistepanyuk** [comment]
Hi Joao,

for_STEPS means that initial SBtab was modified to make it compatible with
BioNetGen - reactions rates dependent
 on expressions and concentrations defined by expressions were modified.

SBtabVFGEN-master is really copied from github. I have added it because it
is used by convert_Viswan_2018_for_STEPS_optimised_from_SBTAB_to_SBML.R
I could modify this but don't know exactly how to use the link in the main
subcellular workflow repository instead, should it be a relative directory
path
which assumes that  SBtabVFGEN-master directory is installed in the same
parent directory as Model_Viswan_2018 folder?

Best,
Andrey

**Comment by jpgsantos** [comment]
I would prefer to add a comment line telling users to go and download this tool from Andrei's github, maybe specifying the exact commit that we know works. This way if there are any bug fixes in the future the user can have them easily and we guarantee that there is one version that works if there are incompatible changes in his source.

Then you could just write for the user to input the correct path for the code that they downloaded in that file, or warn them that they should download Andrei's code in the "BioNetGen and STEPS" folder with a specific name.

It is a balance between making it easier to use with some extra code in this repository, or making it sliglthy more cumbersome but with less code in this repository and with more likelihood of somewhone getting a bugfixed code in the future. I don't know what is best and leave it up to you to decide.

If nobody else raises any problems until mid next week I will merge it into master.

Best,

João

**Comment by andreistepanyuk** [comment]
I have removed SBtab->SBML converter copy and added links to its github repository.

**Review by jpgsantos — COMMENTED** [review]
Seems OK

**Review by jpgsantos — APPROVED** [review]

**Pull request merged**
